name: ai-hack
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - cuda-cccl=12.6.77
  - cuda-cccl_win-64=12.6.77
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-opencl-dev=12.6.77
  - cuda-profiler-api=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - filelock=3.16.1
  - freetype=2.12.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - intel-openmp=2025.0.0
  - jinja2=3.1.4
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.7.77
  - libcurand-dev=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvfatbin-dev=12.6.77
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libtiff=4.7.0
  - libuv=1.49.2
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.13.4
  - libzlib=1.3.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - networkx=3.4.2
  - openjpeg=2.5.2
  - openssl=3.3.2
  - pillow=10.4.0
  - pip=24.3.1
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.12.7
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - requests=2.32.3
  - setuptools=75.3.0
  - sympy=1.13.3
  - tbb=2021.13.0
  - tk=8.6.13
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucrt=10.0.22621.0
  - urllib3=2.2.3
  - vc=14.3
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wheel=0.45.0
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - astunparse==1.6.3
      - cloudpickle==3.1.0
      - farama-notifications==0.0.4
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.67.1
      - gymnasium==1.0.0
      - h5py==3.12.1
      - keras==3.6.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - namex==0.0.8
      - numpy==2.0.2
      - opt-einsum==3.4.0
      - optree==0.13.0
      - packaging==24.2
      - protobuf==5.28.3
      - pygame==2.6.1
      - pygments==2.18.0
      - rich==13.9.4
      - six==1.16.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.18.0
      - tensorflow-intel==2.18.0
      - termcolor==2.5.0
      - torchaudio==2.4.1
      - torchvision==0.19.1
      - werkzeug==3.1.3
      - wrapt==1.16.0
prefix: C:\Users\corbi\mambaforge\envs\ai-hack
